# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

disclapglm_linkfun <- function(mu) {
    .Call('_disclapmix_disclapglm_linkfun', PACKAGE = 'disclapmix', mu)
}

disclapglm_linkinv <- function(eta) {
    .Call('_disclapmix_disclapglm_linkinv', PACKAGE = 'disclapmix', eta)
}

disclapglm_mu_eta <- function(eta) {
    .Call('_disclapmix_disclapglm_mu_eta', PACKAGE = 'disclapmix', eta)
}

disclapglm_varfunc <- function(mu) {
    .Call('_disclapmix_disclapglm_varfunc', PACKAGE = 'disclapmix', mu)
}

disclapglm_loglikeh <- function(mu, y) {
    .Call('_disclapmix_disclapglm_loglikeh', PACKAGE = 'disclapmix', mu, y)
}

disclapglm_deviance <- function(y, mu, wt) {
    .Call('_disclapmix_disclapglm_deviance', PACKAGE = 'disclapmix', y, mu, wt)
}

rcpp_calculate_haplotype_probabilities_sum_CLASS <- function(fits, allele_range) {
    .Call('_disclapmix_rcpp_calculate_haplotype_probabilities_sum_CLASS', PACKAGE = 'disclapmix', fits, allele_range)
}

rcpp_calculate_haplotype_probabilities_sum_CLASS_Cache <- function(fits, allele_range) {
    .Call('_disclapmix_rcpp_calculate_haplotype_probabilities_sum_CLASS_Cache', PACKAGE = 'disclapmix', fits, allele_range)
}

rcpp_calculate_haplotype_probabilities_sum_binomial <- function(dbs) {
    .Call('_disclapmix_rcpp_calculate_haplotype_probabilities_sum_binomial', PACKAGE = 'disclapmix', dbs)
}

rcpp_calculate_haplotype_probabilities_sum_binomial_compact_dbs <- function(compact_dbs, counts) {
    .Call('_disclapmix_rcpp_calculate_haplotype_probabilities_sum_binomial_compact_dbs', PACKAGE = 'disclapmix', compact_dbs, counts)
}

rcpp_calculate_haplotype_probabilities_sum_pedigrees_compact_dbs <- function(compact_dbs, counts) {
    .Call('_disclapmix_rcpp_calculate_haplotype_probabilities_sum_pedigrees_compact_dbs', PACKAGE = 'disclapmix', compact_dbs, counts)
}

rcpp_hapsums_disclap_normalised <- function(fits, haplotypes) {
    .Call('_disclapmix_rcpp_hapsums_disclap_normalised', PACKAGE = 'disclapmix', fits, haplotypes)
}

rcpp_calculate_haplotype_probabilities_sum <- function(allele_range, y, p, tau) {
    .Call('_disclapmix_rcpp_calculate_haplotype_probabilities_sum', PACKAGE = 'disclapmix', allele_range, y, p, tau)
}

rcpp_calculate_haplotype_probabilities_sum_between <- function(allele_range, y1, y2, p1, p2, tau1, tau2) {
    .Call('_disclapmix_rcpp_calculate_haplotype_probabilities_sum_between', PACKAGE = 'disclapmix', allele_range, y1, y2, p1, p2, tau1, tau2)
}

rcpp_match_quantities <- function(allele_range, y, p, tau) {
    .Call('_disclapmix_rcpp_match_quantities', PACKAGE = 'disclapmix', allele_range, y, p, tau)
}

rcpp_create_design_matrix <- function(x, clusters) {
    .Call('_disclapmix_rcpp_create_design_matrix', PACKAGE = 'disclapmix', x, clusters)
}

rcpp_create_new_weight_vector <- function(vic, loci) {
    .Call('_disclapmix_rcpp_create_new_weight_vector', PACKAGE = 'disclapmix', vic, loci)
}

rcpp_create_response_vector <- function(x, y) {
    .Call('_disclapmix_rcpp_create_response_vector', PACKAGE = 'disclapmix', x, y)
}

rcpp_calculate_wic <- function(x, y, p, tau) {
    .Call('_disclapmix_rcpp_calculate_wic', PACKAGE = 'disclapmix', x, y, p, tau)
}

rcpp_calculate_vic <- function(wic) {
    .Call('_disclapmix_rcpp_calculate_vic', PACKAGE = 'disclapmix', wic)
}

rcpp_calculate_haplotype_probabilities <- function(new_data, y, p, tau) {
    .Call('_disclapmix_rcpp_calculate_haplotype_probabilities', PACKAGE = 'disclapmix', new_data, y, p, tau)
}

rcpp_calculate_haplotype_probabilities_se <- function(new_data, y, theta_clusters, theta_loci, vcov, tau) {
    .Call('_disclapmix_rcpp_calculate_haplotype_probabilities_se', PACKAGE = 'disclapmix', new_data, y, theta_clusters, theta_loci, vcov, tau)
}

rcpp_calculate_haplotype_probabilities_clusterwise <- function(new_data, y, p, tau) {
    .Call('_disclapmix_rcpp_calculate_haplotype_probabilities_clusterwise', PACKAGE = 'disclapmix', new_data, y, p, tau)
}

rcpp_simulate <- function(nsim, y, tau_cumsum, disclap_parameters) {
    .Call('_disclapmix_rcpp_simulate', PACKAGE = 'disclapmix', nsim, y, tau_cumsum, disclap_parameters)
}

rcpp_find_haplotype_in_matrix <- function(subpop, h) {
    .Call('_disclapmix_rcpp_find_haplotype_in_matrix', PACKAGE = 'disclapmix', subpop, h)
}

